### ISSUE TITLE
Psi duplicates certain blocks on Break Block trick

### ISSUE THREAD

**Issue by srohr** [Vazkii/Psi#338]
These blocks include: 
* All vanilla heads/skulls
* A Redstone Furnace, should the hit block be a Thermal Expansion machine
* Possibly other things? 

I found this bug initially in FTB Beyond. I was able to replicate the heads in a test pack with just Psi r1.0-42 & AutoRegLib.

**Comment by JonoColwell** [comment]
This issue is still occurring at least on 1.10.2

**Comment by JonoColwell** [comment]
This issue is still occurring at least on 1.10.2, same issue as #305

**Comment by Vazkii** [comment]
This has been fixed in the latest version.

**Comment by Jacob345k** [comment]
@Vazkii Do you plan to fix this issue in the 1.10.2 version? I'm still having this issue with psi and blocks from the mod "Storage Networks"

**Comment by Vazkii** [comment]
I don't have any plans to update older versions, sorry.

**Comment by Jacob345k** [comment]
@Vazkii Can I pay you to fix it on the 1.10.2? I got like forty bucks, and all i'd need is a way to disable the dig trick
