### ISSUE TITLE
[1.12.2] Tutorial Stuck/Can't learn after updating from Psi-r1.1-64 to 1.1-66

### ISSUE THREAD

**Issue by yanphi** [Vazkii/Psi#467]
Firstly I'd like to apologise if there is a solution to this as after numerous Google searches and looking through fourms, I have yet to encounter this problem.

Psi Version: 1.1-66
AutoRegLib: 1.3-24
Forge Version: 14.23.5.2768

I've updated from Psi 1.1-64 to 1.1-66 in addition to updating the entire modpack to a newer version. After the update, my Psi levels were all reset except it still says I'm level 14 with tutorial level 11 "Block movement" still in learning but all progress is gone and I cannot select level 1 to learn.
![image](https://user-images.githubusercontent.com/5514140/50733622-baca7180-11f5-11e9-9bd4-b10007ec7959.png)

I cannot access the spell programmer as it just says I don't understand it yet I still have my working psi metal CAD and bullets which work with no problem.

**Comment by yrsegal** [comment]
Could you upload the relevant world, so I can take a look?

**Comment by yanphi** [comment]
https://1drv.ms/u/s!AmoiLzqpzq2ag48UueScCjVXAcm5oA

There, I've had to upload it to onedrive as the file was too big.

**Comment by yanphi** [comment]
Also is it possible to have Psi remember the tutorial if I were to use different computers? Because using a different computer would reset Psi and have the tutorial locked despite being Level 25. 

UPDATE: The problem can be fixed by switching into creative mode, creating the relevant spell and casting it but the tutorial progress is still locked.

**Comment by Flanks255** [comment]
This is also happening in 67, in a new world is fine when it reloads your progression, but existing worlds are borked.

**Comment by yrsegal** [comment]
This will *actually* be fixed come next version

**Comment by yanphi** [comment]
I'm not sure if this is also fixed in the next version. But whenever I load into the server, I seem to be losing my progress every time.

**Comment by nearlyNonexistent** [comment]
Still persisting in 68: can't advance past Tutorial 1 - Level 1, as it refuses to give the point for Trick: Debug.

**Comment by yrsegal** [comment]
Was this on a previously bugged world?

**Comment by nearlyNonexistent** [comment]
No, entirely new world.
