### ISSUE TITLE
[1.12.2] Break spell not breaking stone-iron harvest level ores/blocks (and some TileEntities/Machines)

### ISSUE THREAD

**Issue by Fogrits** [Vazkii/Psi#604]
The title explains itself.

I can break Thaumcraft Quartz/Cinnabar ores with a vanilla stone pickaxe with no problem at all, but a simple Break spell can't even mine Chisel blocks (all the non-metal blocks have Stone mining level).

![2020-07-03_16 34 20](https://user-images.githubusercontent.com/14002834/86494392-508f8000-bd4b-11ea-9664-d42f80b04363.png)

Psi version: r1.1-78

PS: I've modified the config file to see if it was something wrong with the mining level I used (4), so I put it on 3 (diamond) to see if I could break it, but no avail)

**Comment by ciqven** [comment]
Greetings,

I have the same issue on my server, running Minecraft 1.12.2 with **Psi-r1.1-78.jar**. The previous version, **1.1.77**, does not have this problem.

Reading the Psi changelog for version 1.1.77 I see the following line:
> Fixed the CAD being able to break any block type

My guess is that this issue is related to this change. If this is the intended behavior, please consider making it a config toggle. Players on my server are often using the psigun as a building tool, and it not being able to break bricks or blocks from the Chisel mod is a huge breaker of workflows :)

Thank you for considering.

**Comment by Kamefrede** [comment]
Pretty sure this issue has been fixed in the latest commit in the 1.12 branch
Just need to get a release build out.

**Comment by 22thomas1** [comment]
I can confirm that this is still an issue in version 78 for 1.12.2, I cannot use the break spell to break stone brick, magma blocks, concrete, chests from Iron chest mod, and furnaces. Im sure there are others but this is all I can think of off the top of my head. It seems to have an issue breaking blocks that don't have a set harvest level assigned (waila).

**Comment by BlueAgent** [comment]
Version `1.12.2-78` was released on May 2nd so doesn't include the fix https://github.com/Vazkii/Psi/pull/573 merged on May 10th (see https://github.com/Vazkii/Psi/pull/592 for fix video).
My PR https://github.com/Vazkii/Psi/pull/540 introduced this bug in an attempt to fix breaking of blocks that require specialized tools (e.g. forestry hives).
Sorry for the inconvenience.

**Comment by Kamefrede** [comment]
Released a build.
